### ISSUE TITLE
[URGENT] Milestone 3 pipeline error

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI-522_City_of_A-Stars_310#60]
Make does not run with error on 3rd script:

```
python scripts/eda_script.py --file_path=data/ --results_path=results/
132 math students were in relationships and 263 were not.
239 portuguese language students were in relationships and 410 were not.
The average total grade for math students in relationships was: 30.43/60
The average total grade for math students not in relationships was: 32.84/60
The average total grade for portuguese students in relationships was: 33.85/60
The average total grade for portuguese students not in relationships was: 35.47/60
Traceback (most recent call last):
  File "scripts/eda_script.py", line 205, in <module>
    main(opt["--file_path"], opt["--results_path"])
  File "scripts/eda_script.py", line 86, in main
    p_1_1 = alt.Chart(df_mat[df_mat['romantic']=="yes"]).transform_density(
  File "C:\Users\7ks42\Anaconda3\lib\site-packages\altair\utils\schemapi.py", line 229, in __getattr__
    return _getattr(attr)
AttributeError: 'Chart' object has no attribute 'transform_density'
make: *** [Makefile:23: results/math_table.csv] Error 1
```

**Comment by anasm-17** [comment]
You need altair v 4.0.1, we had mentioned it under requirements in the readme document.

**Comment by ksedivyhaley** [comment]
Wonderful, `conda install altair` apparently installs 3.2.0.  (-_-)  Successfully upgraded using `pip install altair --upgrade`. Everything works. Thanks!
